name: Build Docker image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Налаштування Buildx для підтримки додаткових функцій та кешування
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          # push: true тільки якщо це не Pull Request
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/bot:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/bot:latest
          # Кешування GHA (GitHub Actions)
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Checkout Infra Repository
        uses: actions/checkout@v4
        with:
          repository: RomanMartynyshyn/eco-infra
          token: ${{ secrets.GH_PAT }}
          path: eco-infra

      - name: Update Image Tag in Deployment
        run: |
          cd eco-infra
          # Оновлюємо тег образу на поточний хеш коміту (короткий або повний)
          sed -i "s|image: .*|image: ${{ secrets.DOCKERHUB_USERNAME }}/bot:${{ github.sha }}|g" eco-bot/deployment.yaml
          
          # Налаштовуємо git для коміту
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          
          # Перевіряємо, чи є зміни, і пушимо
          if [[ -n $(git status -s) ]]; then
            git commit -am "Update image tag to ${{ github.sha }}"
            git push
          else
            echo "No changes to commit"
          fi